version: "3.7"

services:
  php-fpm:
    image: php:8.0-fpm-alpine
    volumes:
      - ./:/app
  nginx:
    image: nginx:alpine
    volumes:
      - ./:/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8888:80"
    depends_on:
      - php-fpm